const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

async function main() {
  await prisma.book.create({
    data: {
      title: "Transit to Scorpio",
      author: "Alan Burt Akers",
      pages: {
        create: [
          {
            pageNum: 1,
            text: "In preparing the strange and remarkable story of Dray Prescot for publication I have become overwhelmed at times with the power and presence of his voice. I have listened to the tapes Geoffrey Dean gave me, over and over again, until I feel I know the man Dray Prescot as much through his voice as by what he reveals in what he says. At times deep and reflective, at others animated and passionate with the fire of his recollections, his voice carries absolute conviction. I cannot vouch for the truth of his story; but if ever a human voice invited belief, then this one does. How the tapes from Africa came into my possession is soon told. Geoffrey Dean is a childhood friend, a gray, prim, dedicated man of fixed habits, yet for the sake of old friendship when he called me from Washington I was glad to speak with him. He is a government man with one of these shadowy organizations related to the State Department and he told me three years ago he had had occasion to go to West Africa to supervise fieldwork in connection with a famine emergency. Many brilliant young men and women go out with the Foreign Aid programs, and Geoffrey told me of one, an idealistic youngster, Dan Fraser, who had been working harder than a man should up-country. Fraser told Geoffrey that one day when the situation was almost impossible with horrific numbers of deaths daily a man staggered out of the African forest. Men were dying everywhere around and there was nothing unusual inthat. But this man was completely naked, badly wounded, and he was white. I met Geoffrey Dean for lunch on a flying visit to Washington. We ate well at an exclusive club. Geoffrey brought the conversation around to his telephone call and went on to say that Fraser, who had almost lost control, was shaken and impressed, profoundly impressed, by this stranger.",
            html: "<p>In preparing the strange and remarkable story of Dray Prescot for publication I have become overwhelmed at times with the power and presence of his voice.</p><p>I have listened to the tapes Geoffrey Dean gave me, over and over again, until I feel I know the man Dray Prescot as much through his voice as by what he reveals in what he says. At times deep and reflective, at others animated and passionate with the fire of his recollections, his voice carries absolute conviction. I cannot vouch for the truth of his story; but if ever a human voice invited belief, then this one does.</p><p>How the tapes from Africa came into my possession is soon told. Geoffrey Dean is a childhood friend, a gray, prim, dedicated man of fixed habits, yet for the sake of old friendship when he called me from Washington I was glad to speak with him. He is a government man with one of these shadowy organizations related to the State Department and he told me three years ago he had had occasion to go to West Africa to supervise fieldwork in connection with a famine emergency. Many brilliant young men and women go out with the Foreign Aid programs, and Geoffrey told me of one, an idealistic youngster, Dan Fraser, who had been working harder than a man should up-country.</p><p>Fraser told Geoffrey that one day when the situation was almost impossible with horrific numbers of deaths daily a man staggered out of the African forest. Men were dying everywhere around and there was nothing unusual inthat. But this man was completely naked, badly wounded, and he was white.</p><p>I met Geoffrey Dean for lunch on a flying visit to Washington. We ate well at an exclusive club. Geoffrey brought the conversation around to his telephone call and went on to say that Fraser, who had almost lost control, was shaken and impressed, profoundly impressed, by this stranger.</p>",
          },
          {
            pageNum: 2,
            text: "The famine was killing people by the thousand, massive epidemics were being staved off by daily miracles, aircraft were encountering near-insuperable difficulties flying in supplies; yet in the middle of this chaos and destruction of human life Dan Fraser, an idealistic but seasoned field-worker, was uplifted and strengthened by the character and personality of Dray Prescot. He had given Prescot food and water and bound up his wounds. Prescot could apparently live on next to nothing, his wounds healed rapidly, and when he realized the famine emergency resolutely refused any special treatment. In return Fraser handed across his cassette tape recorder in order that Prescot might record anything he wished. Prescot had a purpose; Fraser said he could see. “Dan said he was saved by Prescot. They were miles from anywhere and he’d been alone. The strength, the calmness, the vitality of Dray Prescot was amazing. He was a little above middle height with shoulders that made Dan’s eyes pop. His hair was brown, and so were his eyes, and they were level and, according to Dan, oddly dominating. Dan sensed an abrasive honesty, a fearless courage, about him. The man was a dynamo, by Dan’s account.” Geoffrey pushed the pile of cassettes over to me across that expensive table with the wine glasses and the silver and fine china and the remains of a first-class meal. Outside that exclusive club Washington, the whole of the United States, seemed as far away, suddenly, as the wilderness of Africa from which these tapes had come. Dray Prescot told Dan Fraser if he did not hear from him inside three years he could do as he saw fit with the tapes. The possibility that they might see publication gave Dray Prescot a deep inner satisfaction, a sense of purpose that Fraser felt held more significance than this mysterious stranger would reveal.",
            html: "<p>The famine was killing people by the thousand, massive epidemics were being staved off by daily miracles, aircraft were encountering near-insuperable difficulties flying in supplies; yet in the middle of this chaos and destruction of human life Dan Fraser, an idealistic but seasoned field-worker, was uplifted and strengthened by the character and personality of Dray Prescot. He had given Prescot food and water and bound up his wounds. Prescot could apparently live on next to nothing, his wounds healed rapidly, and when he realized the famine emergency resolutely refused any special treatment. In return Fraser handed across his cassette tape recorder in order that Prescot might record anything he wished. Prescot had a purpose; Fraser said he could see.</p><p>“Dan said he was saved by Prescot. They were miles from anywhere and he’d been alone. The strength, the calmness, the vitality of Dray Prescot was amazing. He was a little above middle height with shoulders that made Dan’s eyes pop. His hair was brown, and so were his eyes, and they were level and, according to Dan, oddly dominating. Dan sensed an abrasive honesty, a fearless courage, about him. The man was a dynamo, by Dan’s account.”</p><p>Geoffrey pushed the pile of cassettes over to me across that expensive table with the wine glasses and the silver and fine china and the remains of a first-class meal. Outside that exclusive club Washington, the whole of the United States, seemed as far away, suddenly, as the wilderness of Africa from which these tapes had come.</p><p>Dray Prescot told Dan Fraser if he did not hear from him inside three years he could do as he saw fit with the tapes. The possibility that they might see publication gave Dray Prescot a deep inner satisfaction, a sense of purpose that Fraser felt held more significance than this mysterious stranger would reveal.</p>",
          },
          {
            pageNum: 3,
            text: "Fraser was extremely busy with the famine — I gathered more from what Geoffrey did not say that the end of the boy’s nervous resources was close — and only the appearance of Dray Prescot had saved an ugly situation from sliding into a disaster that would have had international repercussions. Geoffrey Dean speaks little of his work; but I believe a great deal of foreign health and happiness is owed directly to him. “I promised to abide by the conditions laid down by Dan Fraser, who would, in any case, have absolutely refused me permission to take the tapes back to America had he not known I would respect his wishes and the wishes of Dray Prescot.” Geoffrey, I had always thought and saw nothing to make me change my mind, had little imagination. He went on: “That famine was a bad one, Alan. Dan had too much to do. When I arrived, Dray Prescot had gone. We were both hellishly busy. Dan did say that he’d seen Prescot, at night, beneath those African stars, staring up, and he’d felt an unease at the big man’s expression.”",
            html: "<p>Fraser was extremely busy with the famine — I gathered more from what Geoffrey did not say that the end of the boy’s nervous resources was close — and only the appearance of Dray Prescot had saved an ugly situation from sliding into a disaster that would have had international repercussions. Geoffrey Dean speaks little of his work; but I believe a great deal of foreign health and happiness is owed directly to him.</p><p>“I promised to abide by the conditions laid down by Dan Fraser, who would, in any case, have absolutely refused me permission to take the tapes back to America had he not known I would respect his wishes and the wishes of Dray Prescot.”</p><p>Geoffrey, I had always thought and saw nothing to make me change my mind, had little imagination. He went on: “That famine was a bad one, Alan. Dan had too much to do. When I arrived, Dray Prescot had gone. We were both hellishly busy. Dan did say that he’d seen Prescot, at night, beneath those African stars, staring up, and he’d felt an unease at the big man’s expression.”</p>",
          },
          {
            pageNum: 4,
            text: "He touched the cassettes with the tip of his finger. “So — here they are. You’ll know what to do with them.” And so I present in book form a transcript of the tapes from Africa. The story they tell is remarkable. I have edited as little as possible. I believe you will detect from the textual evidence how Dray Prescot swings from the expressions of one age to that of another, freely, without any feeling of anachronism. I have omitted much that he says of the customs and conditions of Kregen; but it is my hope that one day a fuller transcript will be possible.",
            html: "<p>He touched the cassettes with the tip of his finger.</p><p>“So — here they are. You’ll know what to do with them.”</p><p>And so I present in book form a transcript of the tapes from Africa. The story they tell is remarkable. I have edited as little as possible. I believe you will detect from the textual evidence how Dray Prescot swings from the expressions of one age to that of another, freely, without any feeling of anachronism. I have omitted much that he says of the customs and conditions of Kregen; but it is my hope that one day a fuller transcript will be possible.</p>",
          },
          {
            pageNum: 5,
            text: "The last cassette ends abruptly in mid-sentence. The tapes are being published in the hope that anyone who may be able to shed some light on their extraordinary contents will come forward. Somehow, and I cannot explain this, I believe that is why Dray Prescot told his story in the midst of famine and epidemic. There is more to learn of that strange and enigmatic figure, I am confident. Fraser is a young man dedicated to helping the less fortunate of the world, and Geoffrey Dean is a civil servant quite devoid of imagination. I cannot believe that either of them would have faked these tapes. They are presented in the conviction that however much lacking in proof they may be, what they tell is a real story that really did happen to Dray Prescot on a world many millions of miles from Earth.",
            html: "<p>The last cassette ends abruptly in mid-sentence.</p><p>The tapes are being published in the hope that anyone who may be able to shed some light on their extraordinary contents will come forward. Somehow, and I cannot explain this, I believe that is why Dray Prescot told his story in the midst of famine and epidemic. There is more to learn of that strange and enigmatic figure, I am confident.</p><p>Fraser is a young man dedicated to helping the less fortunate of the world, and Geoffrey Dean is a civil servant quite devoid of imagination. I cannot believe that either of them would have faked these tapes. They are presented in the conviction that however much lacking in proof they may be, what they tell is a real story that really did happen to Dray Prescot on a world many millions of miles from Earth.</p>",
          },
        ],
      },
    },
  });

  await prisma.book.create({
    data: {
      title: "Lucille and the Healers",
      author: "Anthony J D Burns",
      pages: {
        create: [
          {
            pageNum: 1,
            text: "A few hours ago, the two men loitering at the Royal Victoria Dock had been subject to considerable curiosity. Their drab, near-identical clothing — both of them sporting brown trench coats and matching trilby hats — suggested the possibility that they were plainclothes detectives. On the other hand, the heavy leather satchels they carried, not to mention their twitchy air of nervousness, made the conclusion that they were not-very-confident burglars seem more likely. Some bets had even been taken, but the passage of time, not to mention the almost offensive dullness of the figures, had taken effect, and to most of the dockworkers they had now become as natural and uninteresting a feature of the background as the loading-cranes, the rusty barges, and the murky waters of the Thames. The loiterers themselves, however, were becoming more agitated with each passing second, and less cautious in their whispering. If any passing docker had still been curious enough, he might have heard the following without taking any great effort to eavesdrop: “Damn Yank ship ought to’ve been in ages ago,” declared the younger of the two, glaring almost accusingly at his watch. “It’ll be past sunset by the time it puts in, if it ever does. What the ’ell are we goin’ to do then?” “We do our job, lad,” answered his colleague, with rather forced calm. “This is your first field euthanasia, I suppose?” “Yeah, and I ’adn’t expected I’d be doin’ it in the dead of night. If that blasted boat had come in on time—”",
            html: "<p>A few hours ago, the two men loitering at the Royal Victoria Dock had been subject to considerable curiosity. Their drab, near-identical clothing — both of them sporting brown trench coats and matching trilby hats — suggested the possibility that they were plainclothes detectives. On the other hand, the heavy leather satchels they carried, not to mention their twitchy air of nervousness, made the conclusion that they were not-very-confident burglars seem more likely. Some bets had even been taken, but the passage of time, not to mention the almost offensive dullness of the figures, had taken effect, and to most of the dockworkers they had now become as natural and uninteresting a feature of the background as the loading-cranes, the rusty barges, and the murky waters of the Thames. The loiterers themselves, however, were becoming more agitated with each passing second, and less cautious in their whispering. If any passing docker had still been curious enough, he might have heard the following without taking any great effort to eavesdrop:</p><p>“Damn Yank ship ought to’ve been in ages ago,” declared the younger of the two, glaring almost accusingly at his watch. “It’ll be past sunset by the time it puts in, if it ever does. What the ’ell are we goin’ to do then?”</p><p>“We do our job, lad,” answered his colleague, with rather forced calm. “This is your first field euthanasia, I suppose?”</p><p>“Yeah, and I ’adn’t expected I’d be doin’ it in the dead of night. If that blasted boat had come in on time—”</p>",
          },
          {
            pageNum: 2,
            text: "“We’d have ’ad an easy time of it, sure. Still, nothin’ like a baptism of fire, eh lad?” he commented, with an unreassuring smirk. “Just think: if you survive tonight—” “It ain’t funny, you old—” “Keep a civil tongue, boy. Dunno what you’re so jumpy for, anyhow. You got your Winchester, ’aven’t you?” “Yeah,” he answered, grasping for the sawed-off shotgun beneath his coat. “But that’s goin’ to be a fat lot of good if we have to deal with it after nightfall, ain’t it?” “Well, we’ve got the rest of the gear,” the senior man reminded him, hefting his satchel. “Ways and means, lad. Ways and means.” “And what if it’s expecting us, and gets the jump on us first?” “Bloody ray of sunshine, you are. The Ligeia ’asn’t reported no trouble, so that means it can’t have been feedin’ off the crew, or they’d have sent out an SOS. Can’t have ’ad more than a nibble, at any rate. So it’s got to be weak by now, right?”",
            html: "<p>“We’d have ’ad an easy time of it, sure. Still, nothin’ like a baptism of fire, eh lad?” he commented, with an unreassuring smirk. “Just think: if you survive tonight—”</p><p>“It ain’t funny, you old—”</p><p>“Keep a civil tongue, boy. Dunno what you’re so jumpy for, anyhow. You got your Winchester, ’aven’t you?”</p><p>“Yeah,” he answered, grasping for the sawed-off shotgun beneath his coat. “But that’s goin’ to be a fat lot of good if we have to deal with it after nightfall, ain’t it?”</p><p>“Well, we’ve got the rest of the gear,” the senior man reminded him, hefting his satchel. “Ways and means, lad. Ways and means.”</p><p>“And what if <i>it’s</i> expecting us, and gets the jump on us first?”</p><p>“Bloody ray of sunshine, you are. The <i>Ligeia</i> ’asn’t reported no trouble, so that means it can’t have been feedin’ off the crew, or they’d have sent out an SOS. Can’t have ’ad more than a nibble, at any rate. So it’s got to be weak by now, right?”</p>",
          },
          {
            pageNum: 3,
            text: "“Right, not to mention bleedin’ ravenous. And what if she puts in after midnight? Didn’t the lady who gave us the briefing say they get stronger then, never mind whether or not they’ve been feedin’?” “We got hours till midnight, you stupid son of—” “Oh, you want to bet it can’t take that much longer?” They both looked to the skyline, now gloriously dappled with rosy tints that the failing sunlight had painted across the vast canvas of London’s air pollution. It was a fit subject for Monet, but to these observers it was an evil omen indeed, and even the older man could not suppress a pang of nauseous dread. In all his days as a Healer, and in spite of his show of confidence, he had never before been required to perform field euthanasia upon a fully active carrier, not to mention a carrier that knew full well it was being hunted. Coward though he was, the youngster had a point, and the senior Healer could not help sympathising with his next wish: “With any luck, the bloody ship’s sunk in the Channel.”",
            html: "<p>“Right, not to mention bleedin’ ravenous. And what if she puts in after midnight? Didn’t the lady who gave us the briefing say they get stronger then, never mind whether or not they’ve been feedin’?”</p><p>“We got hours till midnight, you stupid son of—”</p><p>“Oh, you want to bet it can’t take that much longer?”</p><p>They both looked to the skyline, now gloriously dappled with rosy tints that the failing sunlight had painted across the vast canvas of London’s air pollution. It was a fit subject for Monet, but to these observers it was an evil omen indeed, and even the older man could not suppress a pang of nauseous dread. In all his days as a Healer, and in spite of his show of confidence, he had never before been required to perform field euthanasia upon a fully active carrier, not to mention a carrier that knew full well it was being hunted. Coward though he was, the youngster had a point, and the senior Healer could not help sympathising with his next wish:</p><p>“With any luck, the bloody ship’s sunk in the Channel.”</p>",
          },
          {
            pageNum: 4,
            text: "“God willing. You got any change, lad? I reckon I’ll call Radlett HQ — see if they’ve got any news on it. Meantime, you can chase up the harbourmaster. See what he’s got to say. Be discreet, mind. We’re customs men, remember? Special orders to search her for smuggled goods soon as she comes in. Got your official papers?” “’Course I ’ave,” he answered, passing a few coins to his associate. “It’ll be alright with the harbourmaster, d’you think? No awkward questions?” “Don’t fret. Major Drayton’s put the fix in at the Home Office. Getting aboard her’s goin’ to be the easy part, trust me.” “Or not, as the case may be,” quipped the younger healer, gazing down-river upon a panorama that remained stubbornly free of American merchant vessels. “Yeah. Well... let’s be about it, then,” ordered the senior Healer, who set off in search of a telephone box whilst his assistant made for the warehouses. When they were both out of earshot, a docker who had been unloading a nearby barge turned to his workmate and gave him his short but concise interpretation of the curious scene: “Right. You owe me half a crown, mate.”",
            html: "<p>“God willing. You got any change, lad? I reckon I’ll call Radlett HQ — see if they’ve got any news on it. Meantime, you can chase up the harbourmaster. See what he’s got to say. Be discreet, mind. We’re customs men, remember? Special orders to search her for smuggled goods soon as she comes in. Got your official papers?”</p><p>“’Course I ’ave,” he answered, passing a few coins to his associate. “It’ll be alright with the harbourmaster, d’you think? No awkward questions?”</p><p>“Don’t fret. Major Drayton’s put the fix in at the Home Office. Getting aboard her’s goin’ to be the <i>easy</i> part, trust me.”</p><p>“Or not, as the case may be,” quipped the younger healer, gazing down-river upon a panorama that remained stubbornly free of American merchant vessels.</p><p>“Yeah. Well... let’s be about it, then,” ordered the senior Healer, who set off in search of a telephone box whilst his assistant made for the warehouses. When they were both out of earshot, a docker who had been unloading a nearby barge turned to his workmate and gave him his short but concise interpretation of the curious scene:</p>",
          },
          {
            pageNum: 5,
            text: "“Oh, and ’ow d’you work that out, then?” “One of ’em said ‘Home Office’, that’s how. Means they’re coppers, sure enough, so I win the bet, see?” “That so? And why would coppers be passin’ themselves off as customs men, or are you pretendin’ you didn’t hear that bit?” “Well...” he replied, not very confidently. “It might be some hush-hush bit of business. Security, like. Maybe some foreign spy stowed away on the Ligeia, and they’re waitin’ to pick him up before he gets loose in the country.” “Poor lookout for the country if you’re not talkin’ a load of old rubbish, Bill. The Ligeia stopped early, at Tilbury docks. Engine trouble, or so I heard.” “Did it? Oughtn’t we to have told ’em, then?” “Prob’ly,” he answered, without commitment, “but I’ve been hard at it all bloody day and if I don’t get some beer down me throat in the next five minutes I’m liable to bite me own arm and start drinkin’ the blood, like what the Ancient Mariner did.”",
            html: "<p>“Oh, and ’ow d’you work that out, then?”</p><p>“One of ’em said ‘Home Office’, that’s how. Means they’re coppers, sure enough, so I win the bet, see?”</p><p>“That so? And why would coppers be passin’ themselves off as customs men, or are you pretendin’ you didn’t hear that bit?”</p><p>“Well...” he replied, not very confidently. “It might be some hush-hush bit of business. Security, like. Maybe some foreign spy stowed away on the <i>Ligeia</i>, and they’re waitin’ to pick him up before he gets loose in the country.”</p><p>“Poor lookout for the country if you’re not talkin’ a load of old rubbish, Bill. The <i>Ligeia</i> stopped early, at Tilbury docks. Engine trouble, or so I heard.”</p><p>“Did it? Oughtn’t we to have told ’em, then?”</p><p>“Prob’ly,” he answered, without commitment, “but I’ve been hard at it all bloody day and if I don’t get some beer down me throat in the next five minutes I’m liable to bite me own arm and start drinkin’ the blood, like what the Ancient Mariner did.”</p>",
          },
        ],
      },
    },
  });
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (e) => {
    console.error(e);
    await prisma.$disconnect();
    process.exit(1);
  });
